/**
 * Renderer-side engine metadata mirror (no EngineClass).
 * Canonical ids: vieneu | v3nano | edge
 */

export const ENGINE_META = Object.freeze({
    vieneu: Object.freeze({
        id: 'vieneu',
        family: 'vieneu',
        displayName: 'VieNeu Turbo',
        outputFormat: 'wav',
        mode: 'v3turbo',
        workerMode: 'v3turbo',
        settingsKey: Object.freeze({
            voice: 'voice',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: true,
            pauseScale: true,
        }),
        voiceModes: null,
        readyMessage: 'VieNeu V3 Turbo sẵn sàng',
        notReadyAlert: 'Engine chưa sẵn sàng. Kiểm tra Cài đặt → Python.',
        workspaceId: 'batch-workspace',
    }),
    v3nano: Object.freeze({
        id: 'v3nano',
        family: 'vieneu',
        displayName: 'VieNeu Nano',
        outputFormat: 'wav',
        mode: 'v3nano',
        workerMode: 'v3nano',
        settingsKey: Object.freeze({
            voice: 'voiceNano',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: true,
            pauseScale: true,
        }),
        voiceModes: null,
        readyMessage: 'VieNeu V3 Nano sẵn sàng',
        notReadyAlert: 'Engine chưa sẵn sàng. Kiểm tra Cài đặt → Python.',
        workspaceId: 'nano-workspace',
    }),
    edge: Object.freeze({
        id: 'edge',
        family: 'edge',
        displayName: 'Edge TTS',
        outputFormat: 'mp3',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'edgeVoice',
            voiceMode: 'edgeVoiceMode',
            rate: 'edgeRate',
            pitch: 'edgePitch',
            volume: 'edgeVolume',
        }),
        capabilities: Object.freeze({
            speed: false,
            edgeRate: true,
            voiceMode: true,
            volume: false,
            pauseScale: false,
        }),
        voiceModes: Object.freeze([
            { id: 'multilingual', label: 'Đa ngôn ngữ (Multilingual)' },
            { id: 'vietnamese', label: 'Tiếng Việt chuyên (HoaiMy · NamMinh)' },
        ]),
        readyMessage: 'Edge TTS sẵn sàng',
        notReadyAlert: 'Edge TTS chưa sẵn sàng. Kiểm tra Python và kết nối mạng.',
        workspaceId: 'edge-workspace',
    }),
    supertonic: Object.freeze({
        id: 'supertonic',
        family: 'supertonic',
        displayName: 'Supertonic 3',
        outputFormat: 'wav',
        mode: 'supertonic-3',
        workerMode: 'supertonic-3',
        settingsKey: Object.freeze({
            voice: 'supertonicVoice',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: 'supertonicLang',
            steps: 'supertonicSteps',
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: true,
            totalSteps: true,
            voiceClone: false,
        }),
        voiceModes: null,
        languages: Object.freeze([
            { id: 'vi', label: 'Tiếng Việt (vi)' },
            { id: 'en', label: 'English (en)' },
            { id: 'ko', label: '한국어 (ko)' },
            { id: 'ja', label: '日本語 (ja)' },
            { id: 'fr', label: 'Français (fr)' },
            { id: 'de', label: 'Deutsch (de)' },
            { id: 'es', label: 'Español (es)' },
            { id: 'pt', label: 'Português (pt)' },
            { id: 'ru', label: 'Русский (ru)' },
            { id: 'id', label: 'Indonesia (id)' },
            { id: 'it', label: 'Italiano (it)' },
            { id: 'nl', label: 'Nederlands (nl)' },
            { id: 'pl', label: 'Polski (pl)' },
            { id: 'tr', label: 'Türkçe (tr)' },
            { id: 'hi', label: 'हिन्दी (hi)' },
            { id: 'uk', label: 'Українська (uk)' },
            { id: 'ar', label: 'العربية (ar)' },
            { id: 'na', label: 'Tự nhận / fallback (na)' },
        ]),
        readyMessage: 'Supertonic 3 sẵn sàng',
        notReadyAlert: 'Supertonic chưa sẵn sàng. Cài model optional rồi kiểm tra Python (pip install supertonic).',
        workspaceId: 'supertonic-workspace',
    }),
    kitten: Object.freeze({
        id: 'kitten',
        family: 'kitten',
        displayName: 'KittenTTS',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'kittenVoice',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: null,
            steps: null,
            variant: 'kittenVariant',
            speed: 'kittenSpeed',
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: false,
            totalSteps: false,
            modelVariantSelect: true,
            voiceClone: false,
        }),
        voiceModes: null,
        variants: Object.freeze([
            { id: 'mini', label: 'Mini (80M)' },
            { id: 'micro', label: 'Micro (40M)' },
            { id: 'nano', label: 'Nano (15M fp32)' },
            { id: 'nano-int8', label: 'Nano INT8 (15M)' },
        ]),
        languages: Object.freeze([
            { id: 'en', label: 'English (en) — official' },
        ]),
        readyMessage: 'KittenTTS sẵn sàng',
        notReadyAlert: 'KittenTTS chưa sẵn sàng. Cài variant + pip install kittentts wheel.',
        workspaceId: 'kitten-workspace',
    }),
    kokoro: Object.freeze({
        id: 'kokoro',
        family: 'kokoro',
        displayName: 'Kokoro',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'kokoroVoice',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: null,
            steps: null,
            variant: 'kokoroVariant',
            speed: 'kokoroSpeed',
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: false,
            totalSteps: false,
            modelVariantSelect: true,
            voiceClone: false,
        }),
        voiceModes: null,
        variants: Object.freeze([
            { id: 'int8', label: 'INT8 (~80MB · mặc định)' },
            { id: 'fp32', label: 'FP32 (~310MB)' },
        ]),
        languages: Object.freeze([
            { id: 'en', label: 'English (en) — product focus' },
        ]),
        readyMessage: 'Kokoro sẵn sàng',
        notReadyAlert: 'Kokoro chưa sẵn sàng. Cài variant + pip install -r python/requirements-kokoro.txt (cần espeak-ng).',
        workspaceId: 'kokoro-workspace',
    }),
    piper: Object.freeze({
        id: 'piper',
        family: 'piper',
        displayName: 'Piper',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'piperVoice',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: null,
            steps: null,
            variant: 'piperVariant',
            speed: 'piperSpeed',
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: false,
            totalSteps: false,
            modelVariantSelect: true,
            voiceClone: false,
        }),
        voiceModes: null,
        /** Populated from official voices.json via piperListCatalog */
        variants: null,
        catalogDriven: true,
        languages: Object.freeze([
            { id: 'en', label: 'English' },
            { id: 'vi', label: 'Vietnamese (nếu có trong catalog)' },
        ]),
        readyMessage: 'Piper sẵn sàng',
        notReadyAlert: 'Piper chưa sẵn sàng. Cài optional runtime + voice (xem giấy phép trước).',
        workspaceId: 'piper-workspace',
        licenseInstallWarning: 'Thành phần này sử dụng giấy phép riêng. Hãy xem thông tin giấy phép trước khi cài.',
    }),
    chatterbox: Object.freeze({
        id: 'chatterbox',
        family: 'chatterbox',
        displayName: 'Chatterbox',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'chatterboxRef',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: null,
            steps: null,
            variant: 'chatterboxVariant',
            speed: null,
            ref: 'chatterboxRef',
        }),
        capabilities: Object.freeze({
            speed: false,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: false,
            totalSteps: false,
            modelVariantSelect: true,
            voiceClone: true,
            expressionTags: true,
        }),
        voiceModes: null,
        variants: Object.freeze([
            Object.freeze({ id: 'nano', label: 'Nano (110M · CPU-friendly)' }),
            Object.freeze({ id: 'turbo', label: 'Turbo (350M · clone + biểu cảm)' }),
        ]),
        variantProfiles: Object.freeze({
            nano: Object.freeze({
                subtitle: 'English biểu cảm · CPU-friendly',
                strengths: Object.freeze([
                    'English.',
                    'Nhẹ hơn các Chatterbox lớn.',
                    'Hướng tới on-device/CPU.',
                    'Có khả năng biểu cảm theo upstream.',
                    'Phù hợp dialogue và narration.',
                ]),
                weaknesses: Object.freeze([
                    'English.',
                    'Không phù hợp Vietnamese.',
                    'Runtime PyTorch vẫn nặng hơn ONNX engines.',
                    'Model nhỏ có giới hạn so với Turbo.',
                ]),
                bestFor: Object.freeze([
                    'English.',
                    'Máy không GPU mạnh.',
                    'Dialogue.',
                    'Nội dung cần biểu cảm.',
                ]),
                avoidWhen: Object.freeze([
                    'Vietnamese → VieNeu/Supertonic.',
                    'English thuần tốc độ → Kokoro/Kitten.',
                    'Clone English mạnh → Turbo.',
                ]),
            }),
            turbo: Object.freeze({
                subtitle: 'English clone voice · Biểu cảm mạnh',
                strengths: Object.freeze([
                    'Voice cloning English.',
                    'Biểu cảm.',
                    'Paralinguistic tags theo upstream.',
                    'Phù hợp character/dialogue/narration sáng tạo.',
                ]),
                weaknesses: Object.freeze([
                    'Nặng hơn Nano.',
                    'GPU giúp trải nghiệm tốt hơn.',
                    'Không Vietnamese official.',
                    'Runtime lớn hơn ONNX models.',
                ]),
                bestFor: Object.freeze([
                    'Clone English.',
                    'Character voice.',
                    'Dialogue.',
                    'PC có GPU phù hợp.',
                ]),
                avoidWhen: Object.freeze([
                    'Vietnamese → VieNeu.',
                    'CPU nhẹ → Nano/Kokoro/Kitten.',
                ]),
            }),
        }),
        expressionTagSource: 'electron/data/chatterbox-nano-tags.json',
        languages: Object.freeze([
            { id: 'en', label: 'English (en) — only' },
        ]),
        readyMessage: 'Chatterbox sẵn sàng',
        notReadyAlert: 'Chatterbox chưa sẵn sàng. Cài isolated runtime + variant Nano hoặc Turbo.',
        workspaceId: 'chatterbox-workspace',
        modelVariant: 'nano',
    }),
    qwen3: Object.freeze({
        id: 'qwen3',
        family: 'qwen3',
        displayName: 'Qwen3-TTS 0.6B',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'qwen3Voice',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: 'qwen3Lang',
            steps: null,
            variant: 'qwen3Variant',
            speed: null,
            ref: 'qwen3Ref',
            refText: 'qwen3RefText',
            instruct: 'qwen3Instruct',
        }),
        capabilities: Object.freeze({
            speed: false,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: true,
            totalSteps: false,
            modelVariantSelect: true,
            voiceClone: true,
            expressionTags: false,
            voiceDesign: false,
            instruct: true,
        }),
        voiceModes: null,
        variants: Object.freeze([
            Object.freeze({ id: '0.6b-custom', label: '0.6B CustomVoice (preset speakers)' }),
            Object.freeze({ id: '0.6b-base', label: '0.6B Base (voice clone)' }),
        ]),
        languages: Object.freeze([
            { id: 'Auto', label: 'Auto' },
            { id: 'Chinese', label: 'Chinese' },
            { id: 'English', label: 'English' },
            { id: 'Japanese', label: 'Japanese' },
            { id: 'Korean', label: 'Korean' },
            { id: 'German', label: 'German' },
            { id: 'French', label: 'French' },
            { id: 'Russian', label: 'Russian' },
            { id: 'Portuguese', label: 'Portuguese' },
            { id: 'Spanish', label: 'Spanish' },
            { id: 'Italian', label: 'Italian' },
            { id: 'Vietnamese', label: 'Vietnamese (Unsupported — thử nghiệm)', unsupported: true },
        ]),
        speakers: Object.freeze([
            { id: 'Vivian', label: 'Vivian — Bright young female (Chinese)' },
            { id: 'Serena', label: 'Serena — Warm gentle female (Chinese)' },
            { id: 'Uncle_Fu', label: 'Uncle_Fu — Seasoned male (Chinese)' },
            { id: 'Dylan', label: 'Dylan — Youthful Beijing male (Chinese)' },
            { id: 'Eric', label: 'Eric — Lively Chengdu male (Chinese)' },
            { id: 'Ryan', label: 'Ryan — Dynamic male (English)' },
            { id: 'Aiden', label: 'Aiden — Sunny American male (English)' },
            { id: 'Ono_Anna', label: 'Ono_Anna — Playful female (Japanese)' },
            { id: 'Sohee', label: 'Sohee — Warm female (Korean)' },
        ]),
        viWarn: 'Model này không hỗ trợ tiếng Việt chính thức. Khepree khuyên dùng VieNeu hoặc Supertonic.',
        readyMessage: 'Qwen3-TTS 0.6B sẵn sàng',
        notReadyAlert: 'Qwen3-TTS chưa sẵn sàng. Cài isolated runtime + variant 0.6B Custom hoặc Base.',
        workspaceId: 'qwen3-workspace',
        modelVariant: '0.6b-custom',
    }),
    spark: Object.freeze({
        id: 'spark',
        family: 'spark',
        displayName: 'Spark-TTS 0.5B',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'sparkMode',
            voiceMode: 'sparkMode',
            rate: null,
            pitch: 'sparkPitch',
            volume: null,
            lang: 'sparkLang',
            steps: null,
            variant: null,
            speed: null,
            ref: 'sparkRef',
            refText: 'sparkRefText',
            gender: 'sparkGender',
            speedLevel: 'sparkSpeedLevel',
        }),
        capabilities: Object.freeze({
            speed: false,
            edgeRate: false,
            voiceMode: true,
            volume: false,
            pauseScale: false,
            languageSelect: true,
            totalSteps: false,
            modelVariantSelect: false,
            voiceClone: true,
            expressionTags: false,
            voiceDesign: false,
            speakerControls: true,
        }),
        voiceModes: Object.freeze([
            Object.freeze({ id: 'clone', label: 'Zero-shot voice clone' }),
            Object.freeze({ id: 'create', label: 'Voice creation (gender/pitch/speed)' }),
        ]),
        variants: null,
        languages: Object.freeze([
            { id: 'Chinese', label: 'Chinese' },
            { id: 'English', label: 'English' },
            { id: 'Vietnamese', label: 'Vietnamese (Unsupported — thử nghiệm)', unsupported: true },
        ]),
        genders: Object.freeze([
            { id: 'male', label: 'male' },
            { id: 'female', label: 'female' },
        ]),
        levels: Object.freeze([
            { id: 'very_low', label: 'very low' },
            { id: 'low', label: 'low' },
            { id: 'moderate', label: 'moderate' },
            { id: 'high', label: 'high' },
            { id: 'very_high', label: 'very high' },
        ]),
        viWarn: 'Model này không hỗ trợ tiếng Việt chính thức. Khepree khuyên dùng VieNeu hoặc Supertonic.',
        readyMessage: 'Spark-TTS 0.5B sẵn sàng',
        notReadyAlert: 'Spark-TTS chưa sẵn sàng. Cài isolated runtime + model 0.5B.',
        workspaceId: 'spark-workspace',
        modelVariant: '0.5b',
    }),
    'gpt-sovits': Object.freeze({
        id: 'gpt-sovits',
        family: 'gpt-sovits',
        category: 'voice-lab',
        displayName: 'GPT-SoVITS',
        outputFormat: 'wav',
        mode: null,
        workerMode: null,
        settingsKey: Object.freeze({
            voice: 'gptSovitsProfile',
            voiceMode: null,
            rate: null,
            pitch: null,
            volume: null,
            lang: 'gptSovitsTextLang',
            steps: null,
            variant: null,
            speed: null,
            ref: 'gptSovitsRef',
            refText: 'gptSovitsRefText',
            refLang: 'gptSovitsRefLang',
            gptCkpt: 'gptSovitsGptCkpt',
            sovitsCkpt: 'gptSovitsSovitsCkpt',
        }),
        capabilities: Object.freeze({
            speed: true,
            edgeRate: false,
            voiceMode: false,
            volume: false,
            pauseScale: false,
            languageSelect: true,
            totalSteps: false,
            modelVariantSelect: false,
            voiceClone: true,
            expressionTags: false,
            voiceDesign: false,
            speakerControls: false,
            voiceProfiles: true,
            customCheckpoints: true,
        }),
        voiceModes: null,
        variants: null,
        languages: Object.freeze([
            { id: 'auto', label: 'Auto' },
            { id: 'en', label: 'English' },
            { id: 'zh', label: 'Chinese' },
            { id: 'ja', label: 'Japanese' },
            { id: 'yue', label: 'Cantonese' },
            { id: 'ko', label: 'Korean' },
            { id: 'vi', label: 'Vietnamese (Unsupported — thử nghiệm)', unsupported: true },
        ]),
        voiceProfileAck: 'Tôi có quyền sử dụng giọng/reference audio này.',
        viWarn: 'GPT-SoVITS checkpoint/upstream hiện tại không quảng cáo tiếng Việt chính thức. Khepree khuyên dùng VieNeu.',
        readyMessage: 'GPT-SoVITS Voice Lab sẵn sàng',
        notReadyAlert: 'GPT-SoVITS chưa sẵn sàng. Cài Voice Lab runtime + chọn GPT/SoVITS checkpoint.',
        workspaceId: 'gpt-sovits-workspace',
        modelVariant: 'infer',
    }),
});

const ALIASES = Object.freeze({
    'vieneu-turbo': 'vieneu',
    v3turbo: 'vieneu',
    'vieneu-nano': 'v3nano',
    'chatterbox-nano': 'chatterbox',
    'chatterbox-turbo': 'chatterbox',
    'qwen3-tts': 'qwen3',
    'spark-tts': 'spark',
    gptsovits: 'gpt-sovits',
    'gpt_sovits': 'gpt-sovits',
});

export function resolveEngineId(raw) {
    const id = String(raw || '').trim();
    if (ENGINE_META[id]) return id;
    return ALIASES[id] || 'vieneu';
}

export function getEngineMeta(engineId) {
    return ENGINE_META[resolveEngineId(engineId)];
}

export const ENGINE_IDS = Object.freeze(Object.keys(ENGINE_META));
